# DataSource config
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/chooeat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  properties:
  hibernate:
  show-sql: true
  format_sql: true

# application.properties
server.port: 8080